language: python

install:
- uname -a
- lsb_release -a
- pypy --version
- sudo touch /etc/suid-debug
# Travis has a python3, but not the bin/python3 command
- sudo apt-get -y install libffi-dev btrfs-tools python3-minimal user-mode-linux
- which python3
# Those exports make sure pip invocations through tox, virtualenv, etc
# hit the cache. Travis is stupid to document manual addition of cli flags
# instead of exporting those vars (or shipping a pip.conf).
- export PIP_USE_MIRRORS=true
- export PIP_DOWNLOAD_CACHE=~/.cache/pip
- pip install cffi tox
#- wget https://raw.github.com/g2p/kernels/master/linux.uml
#- chmod +x linux.uml
#- git clone https://github.com/g2p/vido.git
#- export GETROOT="$PWD/vido/vido --kernel=./linux.uml --"

# tox has some advantages over travis runners:
# it tests installation from the sdist, which will
# report things like missing header files.

script:
# Travis has PyPy 1.9 which is too old (want a PPA to upgrade).
- time tox -e pypy || echo "Ignoring PyPy failures on Travis"
- time tox -e py3.4,py33,py27,py32

